#!/usr/bin/env python

import rospy
import subprocess
import signal

child = subprocess.Popen(["roslaunch","cartographer_ros",
"demo_backpack_2d_localization_start_trajectory.launch",
"load_state_filename:=b2-2016-04-05-14-44-52.bag.pbstream",
"bag_filename:=b2-2016-04-27-12-31-41.bag"])
# child.wait() #You can use this line to block the parent process untill the child process finished.

print("parent process")
print(child.poll())

rospy.loginfo('The PID of child: %d', child.pid)
print ("The PID of child:", child.pid)

rospy.sleep(5)

# child.send_signal(signal.SIGINT) #You may also use .terminate() method
# child.terminate()

child2 = subprocess.Popen(["roslaunch","cartographer_ros",
"start_trajectory.launch",])
child.wait()

